//! `skies i18n` for React: assembles every feature's `*.i18n.ts` catalog into one generated resource module.
//!
//! The output imports each catalog and composes `resources` (locale → namespace), the tree an app otherwise wires
//! by hand. It typechecks, so a renamed or removed catalog fails the build; key parity inside a catalog stays with
//! SKYFE011 in the ESLint plugin.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use super::names::ident;
use super::scaffold::relative_path;

/// The generated module, relative to the package's source root.
pub const OUTPUT: &str = "i18n/resources.generated.ts";

/// One discovered catalog: its namespace and the extensionless import path from the output module.
#[derive(Debug, Clone, PartialEq)]
pub struct Catalog {
    pub namespace: String,
    pub import_path: String,
}

pub fn assemble(package: &Path) -> Result<u8> {
    let src = package.join("src");
    let root = if src.is_dir() { src } else { package.to_path_buf() };
    let output = root.join(OUTPUT);
    let out_dir = output.parent().context("output has a parent")?.to_path_buf();

    let mut paths = Vec::new();
    find_catalogs(&root, &mut paths)?;
    paths.sort();
    if paths.is_empty() {
        bail!("no *.i18n.ts catalogs found under {}", root.display());
    }
    let catalogs: Vec<Catalog> = paths
        .iter()
        .map(|path| {
            let file = path.file_name().unwrap_or_default().to_string_lossy();
            let namespace = file.trim_end_matches(".i18n.ts").to_string();
            let import_path = relative_path(&out_dir, &path.with_file_name(format!("{namespace}.i18n")));
            Catalog { namespace, import_path }
        })
        .collect();

    std::fs::create_dir_all(&out_dir)?;
    std::fs::write(&output, render_resources(&catalogs)).with_context(|| format!("writing {}", output.display()))?;
    println!("assembled {} catalog(s) -> {}", catalogs.len(), output.display());
    for catalog in &catalogs {
        println!("  {}  ({})", catalog.namespace, catalog.import_path);
    }
    Ok(0)
}

fn find_catalogs(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
    for entry in std::fs::read_dir(dir).with_context(|| format!("reading {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        let name = entry.file_name();
        if entry.file_type()?.is_dir() {
            if name != "node_modules" {
                find_catalogs(&path, out)?;
            }
        } else if name.to_string_lossy().ends_with(".i18n.ts") {
            out.push(path);
        }
    }
    Ok(())
}

/// Renders the resource module. Catalogs are sorted by namespace so the file is stable across runs and machines.
pub fn render_resources(catalogs: &[Catalog]) -> String {
    let mut sorted = catalogs.to_vec();
    sorted.sort_by(|a, b| a.namespace.cmp(&b.namespace));

    let mut out = String::from(
        "// GENERATED by `skies i18n` — do not edit. Re-run to regenerate after adding/removing a feature.\n",
    );
    for catalog in &sorted {
        let id = ident(&catalog.namespace);
        out += &format!(
            "import {{ ptBR as {id}_ptBR, esES as {id}_esES, enUS as {id}_enUS }} from \"{}\";\n",
            catalog.import_path
        );
    }
    out += "\nexport const resources = {\n";
    for (locale, suffix) in [("en", "enUS"), ("pt", "ptBR"), ("es", "esES")] {
        out += &format!("  {locale}: {{\n");
        for catalog in &sorted {
            let key = serde_json::to_string(&catalog.namespace).unwrap_or_default();
            out += &format!("    {key}: {}_{suffix},\n", ident(&catalog.namespace));
        }
        out += "  },\n";
    }
    out += "} as const;\n";
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn catalog(namespace: &str, import_path: &str) -> Catalog {
        Catalog {
            namespace: namespace.into(),
            import_path: import_path.into(),
        }
    }

    #[test]
    fn composes_the_locale_namespace_tree_in_a_stable_order() {
        let out = render_resources(&[
            catalog("items", "../features/items/items.i18n"),
            catalog("bookings", "../features/bookings/bookings.i18n"),
        ]);

        assert!(out.contains(
            "import { ptBR as items_ptBR, esES as items_esES, enUS as items_enUS } from \"../features/items/items.i18n\";"
        ));
        assert!(out.contains("    \"bookings\": bookings_enUS,\n"));
        assert!(out.contains("export const resources"));
        assert!(out.find("bookings_ptBR").unwrap() < out.find("items_ptBR").unwrap());
    }

    #[test]
    fn makes_a_js_safe_identifier_from_a_kebab_namespace() {
        let out = render_resources(&[catalog("user-profile", "./up.i18n")]);
        assert!(out.contains("user_profile_enUS"));
        assert!(out.contains("\"user-profile\": user_profile_enUS,"));
    }

    #[test]
    fn discovers_catalogs_under_src_and_writes_the_module() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src/items")).unwrap();
        std::fs::write(dir.path().join("src/items/items.i18n.ts"), "export const enUS = {};").unwrap();

        assemble(dir.path()).unwrap();

        let out = std::fs::read_to_string(dir.path().join("src").join(OUTPUT)).unwrap();
        assert!(out.contains("from \"../items/items.i18n\";"));
    }

    #[test]
    fn fails_when_there_is_nothing_to_assemble() {
        let dir = tempfile::tempdir().unwrap();
        assert!(assemble(dir.path()).is_err());
    }
}
