//! Parity with the 4.x C# CLI: replay the commands that produced `fixtures/golden4` with the Rust binary and
//! compare the trees byte for byte.
//!
//! The fixtures were generated by the 4.x CLI (`skies new Golden`, then from `src/Golden.Api`: module, slice,
//! entity, vo, hub, auth and its three flows, a tenant-scoped entity, crud; plus `new` + `g auth --skip-*`).
//! Every file must be identical except the differences 5.0 makes on purpose, which are listed here one by one:
//! files that are no longer generated, files that were rewritten, known edits applied to the golden copy before
//! comparing, and the new `.specs/` folder.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Paths (relative to the solution) that 5.0 must not generate: the proof ceremony and the CSM/design/hook harness.
fn removed(path: &str) -> bool {
    const PREFIXES: &[&str] = &[".skies/", ".design/", ".claude/", ".config/"];
    const FILES: &[&str] = &["csm.toml", "lefthook.yml", "package.json", "package-lock.json"];
    PREFIXES.iter().any(|prefix| path.starts_with(prefix))
        || FILES.contains(&path)
        || path.ends_with(".Tests.cs")
        || path.ends_with(".spec.toml")
        || path.contains("/Journeys/")
        || path.ends_with("/AvpAssert.cs")
}

/// Rewritten for 5.0; they must exist but are not compared: CI is restore/build/test, and `Skies.toml` declares
/// only workspace, products, and a commented runner.
const REWRITTEN: &[&str] = &[".github/workflows/ci.yml", "Skies.toml"];

/// Not compared: 4.x `g crud` matched the scaffold's commented `//   var catalog = app.MapGroup(...)` line as the
/// module's route group and mapped the slices onto an undeclared `catalog`. 5.0 matches code lines only and declares
/// the group itself (fail-closed) when the module has none.
const CRUD_MODULE: &str = "src/Golden.Api/Modules/Catalog/CatalogModule.cs";

/// Applies the intentional template edits to a golden file, so the rest of the file is still compared exactly.
fn normalize_golden(path: &str, golden: String) -> String {
    let edits: &[(&str, &str)] = match path {
        "AGENTS.md" | "CLAUDE.md" => {
            // The `skies:foundations` block (the CSM workflow) is gone, with the blank line before it.
            let cut = golden
                .find("\n<!-- skies:foundations:start -->")
                .expect("foundations block");
            return golden[..cut].to_string();
        }
        "src/Golden.Api/Golden.Api.csproj" => &[
            (
                "    <!-- Tests live co-located with the slice. The app assembly never compiles them (no test deps\n         ship); the doctor reads them as AdditionalFiles to require each slice has one. -->\n",
                "    <!-- A unit test may live next to the code it tests; the tests project compiles it, the app never\n         does (no test deps ship). -->\n",
            ),
            ("    <AdditionalFiles Include=\"**\\*.Tests.cs\" />\n", ""),
            (
                "    <!-- Clockwork manifests bind every slice to its executable AVP proofs (SKY0030/SKY0031). -->\n    <AdditionalFiles Include=\"**\\*.spec.toml\" />\n",
                "",
            ),
        ],
        "tests/Golden.Tests/Golden.Tests.csproj" => &[
            ("    <PackageReference Include=\"Assay.Net\" Version=\"0.4.0\" />\n", ""),
            (
                "    <!-- Co-located tests: the files live next to the slice in src/, compiled here. -->\n",
                "    <!-- Spec E2E: each .specs/<id>-<slug>/e2e folder holds the black-box cases for one spec's failure\n         modes (namespace Specs.S<id>, display names \"FM-n: ...\"). `skies proof record` runs them. -->\n    <Compile Include=\"..\\..\\.specs\\*\\e2e\\**\\*.cs\" />\n    <!-- Co-located unit tests: the files live next to the code in src/, compiled here. -->\n",
            ),
        ],
        // Ping no longer ships a test, so the seed note stops promising one.
        "src/Golden.Api/Modules/Health/Health.ctx.md" => &[(
            "`Ping` exists so a fresh app has one passing slice + test (SKY0001/SKY0003 green) and a route to curl.",
            "`Ping` exists so a fresh app has one conformant slice (SKY0001 green) and a route to curl.",
        )],
        // `g slice` declares its authorization decision (SKY0022) and fails closed until the owner decides.
        "src/Golden.Api/Modules/Billing/Slices/CreateInvoice.cs"
        | "src/Golden.Api/Modules/Billing/Slices/GetInvoice.cs" => {
            let slice = path.rsplit('/').next().unwrap().trim_end_matches(".cs");
            let from = format!("            .WithName(nameof({slice}));\n");
            let to = format!("            .WithName(nameof({slice}))\n            .RequireAuthorization();\n");
            assert!(golden.contains(&from), "{path}: the golden slice changed shape");
            return golden.replacen(&from, &to, 1);
        }
        // The crud slices name their endpoints (SKY0012), which the 4.x templates forgot.
        path if path.starts_with("src/Golden.Api/Modules/Catalog/Slices/") => {
            let slice = path.rsplit('/').next().unwrap().trim_end_matches(".cs");
            let from = "            .RequireAuthorization();\n";
            assert!(golden.contains(from), "{path}: the golden crud slice changed shape");
            return golden.replacen(from, &format!("            .WithName(nameof({slice}))\n{from}"), 1);
        }
        _ => &[],
    };
    edits.iter().fold(golden, |text, (from, to)| {
        assert!(
            text.contains(from),
            "{path}: the golden no longer contains the edited text {from:?}"
        );
        text.replacen(from, to, 1)
    })
}

/// The only new output: the auth specs, the `.specs/README.md` the template ships, and the ctx skeleton `g module`
/// now writes so a module is doctor-clean (SKY0004) from birth.
fn added(path: &str, expected_specs: &[&str]) -> bool {
    const MODULE_CONTEXTS: &[&str] = &[
        "src/Golden.Api/Modules/Billing/Billing.ctx.md",
        "src/Golden.Api/Modules/Catalog/Catalog.ctx.md",
    ];
    path == ".specs/README.md"
        || MODULE_CONTEXTS.contains(&path)
        || expected_specs
            .iter()
            .any(|spec| path.starts_with(&format!(".specs/{spec}/")))
}

fn skies(dir: &Path, args: &[&str]) {
    let status = Command::new(env!("CARGO_BIN_EXE_skies"))
        .args(args)
        .current_dir(dir)
        .stdout(std::process::Stdio::null())
        .status()
        .expect("run skies");
    assert!(status.success(), "skies {} failed in {}", args.join(" "), dir.display());
}

fn files(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let relative = path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
                out.insert(relative, std::fs::read(&path).unwrap());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

fn fixture(tree: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/golden4")
        .join(tree)
}

/// Compares a generated solution against its golden twin under the rules above.
fn assert_parity(tree: &str, generated: &Path, expected_specs: &[&str]) {
    let golden = files(&fixture(tree));
    let ours = files(generated);

    let mut mismatches = Vec::new();
    for (path, golden_bytes) in &golden {
        let Some(our_bytes) = ours.get(path) else {
            mismatches.push(format!("missing: {path}"));
            continue;
        };
        if REWRITTEN.contains(&path.as_str()) || path == CRUD_MODULE {
            continue;
        }
        let expected = normalize_golden(path, String::from_utf8(golden_bytes.clone()).unwrap());
        if expected.as_bytes() != our_bytes.as_slice() {
            mismatches.push(format!("differs: {path}"));
        }
    }
    for path in ours.keys() {
        assert!(!removed(path), "{tree}: 5.0 must not generate {path}");
        if !golden.contains_key(path) && !added(path, expected_specs) {
            mismatches.push(format!("unexpected: {path}"));
        }
    }
    for spec in expected_specs {
        assert!(
            ours.contains_key(&format!(".specs/{spec}/spec.md")),
            "{tree}: no .specs/{spec}/spec.md"
        );
    }
    assert!(
        mismatches.is_empty(),
        "{tree} diverges from the 4.x golden:\n{}",
        mismatches.join("\n")
    );
}

#[test]
fn the_full_generator_sequence_matches_the_4x_golden() {
    let work = tempfile::tempdir().unwrap();
    skies(work.path(), &["new", "Golden"]);
    let solution = work.path().join("Golden");
    let api = solution.join("src/Golden.Api");
    for args in [
        &["g", "module", "Billing"][..],
        &["g", "slice", "Billing", "CreateInvoice"],
        &["g", "slice", "Billing", "GetInvoice"],
        &["g", "entity", "Billing", "Invoice"],
        &["g", "vo", "Money"],
        &["g", "module", "Catalog"],
        &["g", "hub", "Billing", "Payments"],
        &["g", "auth"],
        &["g", "auth:otp"],
        &["g", "auth:oauth"],
        &["g", "auth:email"],
        &["g", "entity", "Catalog", "Product"],
    ] {
        skies(&api, args);
    }

    // The manual edit the golden history records ("tenant product"): crud needs an ITenantScoped entity.
    let product = api.join("Modules/Catalog/Product.cs");
    let source = std::fs::read_to_string(&product).unwrap();
    let edited = source.replacen("public class Product\n", "public class Product : ITenantScoped\n", 1).replacen(
        "    public Guid Id { get; private set; }\n",
        "    public Guid Id { get; private set; }\n\n    public Guid TenantId { get; set; }\n    public string Name { get; private set; } = \"\";\n",
        1,
    );
    std::fs::write(&product, edited).unwrap();
    skies(&api, &["g", "crud", "Catalog", "Product"]);

    assert_parity(
        "Golden",
        &solution,
        &["0001-auth", "0002-auth-otp", "0003-auth-oauth", "0004-auth-email"],
    );
}

#[test]
fn the_auth_variants_match_the_4x_golden() {
    for (tree, flag) in [
        ("G-skip-tenancy", "--skip-tenancy"),
        ("G-skip-cookies", "--skip-cookies"),
    ] {
        let work = tempfile::tempdir().unwrap();
        skies(work.path(), &["new", "Golden"]);
        let solution = work.path().join("Golden");
        skies(&solution.join("src/Golden.Api"), &["g", "auth", flag]);
        assert_parity(tree, &solution, &["0001-auth"]);
    }
}

#[test]
fn crud_refuses_an_entity_that_is_not_tenant_scoped() {
    let work = tempfile::tempdir().unwrap();
    skies(work.path(), &["new", "Golden"]);
    let api = work.path().join("Golden/src/Golden.Api");
    skies(&api, &["g", "module", "Catalog"]);
    skies(&api, &["g", "entity", "Catalog", "Product"]);

    let output = Command::new(env!("CARGO_BIN_EXE_skies"))
        .args(["g", "crud", "Catalog", "Product"])
        .current_dir(&api)
        .output()
        .unwrap();

    assert_eq!(output.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&output.stderr).contains("Product is not ITenantScoped"));
    assert!(!api.join("Modules/Catalog/Slices").exists());
}
