//! Parity with the 4.x C# CLI: replay the commands that produced `fixtures/golden4` with the Rust binary and
//! compare the trees byte for byte.
//!
//! The fixtures were generated by the 4.x CLI (`skies new Golden`, then from `src/Golden.Api`: module, slice,
//! entity, vo, hub, auth and its three flows, a tenant-scoped entity, crud; plus `new` + `g auth --skip-*`).
//! Every file must be identical except the differences 5.0 makes on purpose, which are listed here one by one:
//! files that are no longer generated, files that were rewritten, known edits applied to the golden copy before
//! comparing, and the new `.specs/` folder.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

/// Paths (relative to the solution) that 5.0 must not generate: the proof ceremony and the CSM/design/hook harness.
fn removed(path: &str) -> bool {
    const PREFIXES: &[&str] = &[".skies/", ".design/", ".claude/", ".config/"];
    const FILES: &[&str] = &["csm.toml", "lefthook.yml", "package.json", "package-lock.json"];
    PREFIXES.iter().any(|prefix| path.starts_with(prefix))
        || FILES.contains(&path)
        || path.ends_with(".Tests.cs")
        || path.ends_with(".spec.toml")
        || path.contains("/Journeys/")
        || path.ends_with("/AvpAssert.cs")
}

/// Rewritten for 5.0; they must exist but are not compared: CI is restore/build/test, and `Skies.toml` declares
/// only workspace, products, and a commented runner.
const REWRITTEN: &[&str] = &[".github/workflows/ci.yml", "Skies.toml"];

/// `g crud` was redesigned for 5.0, so its output is not compared with 4.x; `crud_output_is_doctor_shaped` pins
/// the new shape instead. The 4.x slices assigned public setters and built the entity with `new Product { ... }`,
/// which an `[Entity]` forbids (SKY0014), and mapped onto the module's commented-out group line. In 5.0 crud
/// writes `Open`/`Update`/`RowVersion` into the entity and the slices call them, `List` pages through
/// `ToPageAsync`, and crud declares the route group when the module has none. The entity file is here too
/// because the test's own edit of it differs (a real `OrgId` instead of 4.x's `TenantId { get; set; }`).
fn crud_redesigned(path: &str) -> bool {
    path == "src/Golden.Api/Modules/Catalog/Product.cs"
        || path == "src/Golden.Api/Modules/Catalog/CatalogModule.cs"
        || path.starts_with("src/Golden.Api/Modules/Catalog/Slices/")
}

/// Applies the intentional template edits to a golden file, so the rest of the file is still compared exactly.
fn normalize_golden(tree: &str, path: &str, golden: String) -> String {
    // `g crud` (only the Golden tree runs it) references the EF Core satellite: its List slice pages through
    // ToPageAsync.
    let golden = if tree == "Golden" && path == "src/Golden.Api/Golden.Api.csproj" {
        let last = "    <PackageReference Include=\"Skies.Framework.Mail\" Version=\"4.1.4\" />\n";
        let paging = "    <PackageReference Include=\"Skies.Framework.EntityFrameworkCore\" Version=\"4.1.4\" />\n";
        assert!(golden.contains(last), "{path}: the golden csproj changed shape");
        golden.replacen(last, &format!("{last}{paging}"), 1)
    } else {
        golden
    };
    let edits: &[(&str, &str)] = match path {
        "AGENTS.md" | "CLAUDE.md" => {
            // The `skies:foundations` block (the CSM workflow) is gone, with the blank line before it.
            let cut = golden
                .find("\n<!-- skies:foundations:start -->")
                .expect("foundations block");
            return golden[..cut].to_string();
        }
        "src/Golden.Api/Golden.Api.csproj" => &[
            (
                "    <!-- Tests live co-located with the slice. The app assembly never compiles them (no test deps\n         ship); the doctor reads them as AdditionalFiles to require each slice has one. -->\n",
                "    <!-- A unit test may live next to the code it tests; the tests project compiles it, the app never\n         does (no test deps ship). -->\n",
            ),
            ("    <AdditionalFiles Include=\"**\\*.Tests.cs\" />\n", ""),
            (
                "    <!-- Clockwork manifests bind every slice to its executable AVP proofs (SKY0030/SKY0031). -->\n    <AdditionalFiles Include=\"**\\*.spec.toml\" />\n",
                "",
            ),
        ],
        "tests/Golden.Tests/Golden.Tests.csproj" => &[
            ("    <PackageReference Include=\"Assay.Net\" Version=\"0.4.0\" />\n", ""),
            (
                "    <!-- Co-located tests: the files live next to the slice in src/, compiled here. -->\n",
                "    <!-- Spec E2E: each .specs/<id>-<slug>/e2e folder holds the black-box cases for one spec's failure\n         modes (namespace Specs.S<id>, display names \"FM-n: ...\"). `skies proof record` runs them. -->\n    <Compile Include=\"..\\..\\.specs\\*\\e2e\\**\\*.cs\" />\n    <!-- Co-located unit tests: the files live next to the code in src/, compiled here. -->\n",
            ),
        ],
        // Ping no longer ships a test, so the seed note stops promising one.
        "src/Golden.Api/Modules/Health/Health.ctx.md" => &[(
            "`Ping` exists so a fresh app has one passing slice + test (SKY0001/SKY0003 green) and a route to curl.",
            "`Ping` exists so a fresh app has one conformant slice (SKY0001 green) and a route to curl.",
        )],
        // `g slice` declares its authorization decision (SKY0022) and fails closed until the owner decides.
        "src/Golden.Api/Modules/Billing/Slices/CreateInvoice.cs"
        | "src/Golden.Api/Modules/Billing/Slices/GetInvoice.cs" => {
            let slice = path.rsplit('/').next().unwrap().trim_end_matches(".cs");
            let from = format!("            .WithName(nameof({slice}));\n");
            let to = format!("            .WithName(nameof({slice}))\n            .RequireAuthorization();\n");
            assert!(golden.contains(&from), "{path}: the golden slice changed shape");
            return golden.replacen(&from, &to, 1);
        }
        _ => &[],
    };
    edits.iter().fold(golden, |text, (from, to)| {
        assert!(
            text.contains(from),
            "{path}: the golden no longer contains the edited text {from:?}"
        );
        text.replacen(from, to, 1)
    })
}

/// The only new output: the auth specs, the `.specs/README.md` the template ships, and the ctx skeleton `g module`
/// now writes so a module is doctor-clean (SKY0004) from birth.
fn added(path: &str, expected_specs: &[&str]) -> bool {
    const MODULE_CONTEXTS: &[&str] = &[
        "src/Golden.Api/Modules/Billing/Billing.ctx.md",
        "src/Golden.Api/Modules/Catalog/Catalog.ctx.md",
    ];
    path == ".specs/README.md"
        || MODULE_CONTEXTS.contains(&path)
        || expected_specs
            .iter()
            .any(|spec| path.starts_with(&format!(".specs/{spec}/")))
}

fn skies(dir: &Path, args: &[&str]) {
    let status = Command::new(env!("CARGO_BIN_EXE_skies"))
        .args(args)
        .current_dir(dir)
        .stdout(std::process::Stdio::null())
        .status()
        .expect("run skies");
    assert!(status.success(), "skies {} failed in {}", args.join(" "), dir.display());
}

fn files(root: &Path) -> BTreeMap<String, Vec<u8>> {
    fn walk(root: &Path, dir: &Path, out: &mut BTreeMap<String, Vec<u8>>) {
        for entry in std::fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                walk(root, &path, out);
            } else {
                let relative = path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/");
                out.insert(relative, std::fs::read(&path).unwrap());
            }
        }
    }
    let mut out = BTreeMap::new();
    walk(root, root, &mut out);
    out
}

fn fixture(tree: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/golden4")
        .join(tree)
}

/// Compares a generated solution against its golden twin under the rules above.
fn assert_parity(tree: &str, generated: &Path, expected_specs: &[&str]) {
    let golden = files(&fixture(tree));
    let ours = files(generated);

    let mut mismatches = Vec::new();
    for (path, golden_bytes) in &golden {
        let Some(our_bytes) = ours.get(path) else {
            mismatches.push(format!("missing: {path}"));
            continue;
        };
        if REWRITTEN.contains(&path.as_str()) || crud_redesigned(path) {
            continue;
        }
        let expected = normalize_golden(tree, path, String::from_utf8(golden_bytes.clone()).unwrap());
        if expected.as_bytes() != our_bytes.as_slice() {
            mismatches.push(format!("differs: {path}"));
        }
    }
    for path in ours.keys() {
        assert!(!removed(path), "{tree}: 5.0 must not generate {path}");
        if !golden.contains_key(path) && !added(path, expected_specs) {
            mismatches.push(format!("unexpected: {path}"));
        }
    }
    for spec in expected_specs {
        assert!(
            ours.contains_key(&format!(".specs/{spec}/spec.md")),
            "{tree}: no .specs/{spec}/spec.md"
        );
    }
    assert!(
        mismatches.is_empty(),
        "{tree} diverges from the 4.x golden:\n{}",
        mismatches.join("\n")
    );
}

#[test]
fn the_full_generator_sequence_matches_the_4x_golden() {
    let work = tempfile::tempdir().unwrap();
    skies(work.path(), &["new", "Golden"]);
    let solution = work.path().join("Golden");
    let api = solution.join("src/Golden.Api");
    for args in [
        &["g", "module", "Billing"][..],
        &["g", "slice", "Billing", "CreateInvoice"],
        &["g", "slice", "Billing", "GetInvoice"],
        &["g", "entity", "Billing", "Invoice"],
        &["g", "vo", "Money"],
        &["g", "module", "Catalog"],
        &["g", "hub", "Billing", "Payments"],
        &["g", "auth"],
        &["g", "auth:otp"],
        &["g", "auth:oauth"],
        &["g", "auth:email"],
        &["g", "entity", "Catalog", "Product"],
    ] {
        skies(&api, args);
    }

    // The owner's edit the golden history records ("tenant product"): crud needs an ITenantScoped entity with
    // domain state. 5.0 writes the tenancy the way ITenantScoped documents it (an encapsulated OrgId).
    let product = api.join("Modules/Catalog/Product.cs");
    let source = std::fs::read_to_string(&product).unwrap();
    let edited = source.replacen("public class Product\n", "public class Product : ITenantScoped\n", 1).replacen(
        "    public Guid Id { get; private set; }\n",
        "    public Guid Id { get; private set; }\n\n    public Guid OrgId { get; private set; }\n    public string Name { get; private set; } = \"\";\n",
        1,
    );
    std::fs::write(&product, edited).unwrap();
    skies(&api, &["g", "crud", "Catalog", "Product"]);

    assert_parity(
        "Golden",
        &solution,
        &["0001-auth", "0002-auth-otp", "0003-auth-oauth", "0004-auth-email"],
    );
    crud_output_is_doctor_shaped(&api);
}

/// The 5.0 crud shape that replaces byte parity for the files in `crud_redesigned`: no slice writes a column,
/// the entity carries the members the slices call, and the module maps them under a real (uncommented) group.
fn crud_output_is_doctor_shaped(api: &Path) {
    let read = |path: &str| std::fs::read_to_string(api.join(path)).unwrap();
    let product = read("Modules/Catalog/Product.cs");
    assert!(
        !product.contains("{ get; set; }"),
        "an [Entity] has no public setter (SKY0014)"
    );
    assert!(product.contains(
        "    public static Result<Product> Open(Guid id, string name) =>\n        new Product { Id = id, Name = name }.EnsureValid();\n"
    ));
    assert!(product.contains("    public Result<Product> Update(string name)\n    {\n        Name = name;\n        return EnsureValid();\n    }\n"));
    assert!(product.contains(
        "[System.ComponentModel.DataAnnotations.Timestamp]\n    public byte[]? RowVersion { get; private set; }"
    ));

    let create = read("Modules/Catalog/Slices/CreateProduct.cs");
    assert!(create.contains("var opened = Product.Open(Guid.NewGuid(), input.Name);"));
    assert!(!create.contains("new Product"));
    let update = read("Modules/Catalog/Slices/UpdateProduct.cs");
    assert!(update.contains("var updated = item.Update(input.Name);\n        if (updated.IsFailure)"));
    let list = read("Modules/Catalog/Slices/ListProduct.cs");
    assert!(list.contains(
        "db.Products.OrderBy(e => e.Id)\n            .ToPageAsync(input.Page, input.PageSize, MaxPageSize, ct);"
    ));
    for slice in ["List", "Lookup", "Create", "Update", "Delete"] {
        let source = read(&format!("Modules/Catalog/Slices/{slice}Product.cs"));
        assert!(source.contains(&format!(
            ".WithName(nameof({slice}Product))\n            .RequireAuthorization();"
        )));
    }

    let module = read("Modules/Catalog/CatalogModule.cs");
    assert!(module.contains(
        "        var catalog = app.MapGroup(\"/catalog\").RequireAuthorization();\n        ListProduct.Map(catalog);\n"
    ));
}

#[test]
fn the_auth_variants_match_the_4x_golden() {
    for (tree, flag) in [
        ("G-skip-tenancy", "--skip-tenancy"),
        ("G-skip-cookies", "--skip-cookies"),
    ] {
        let work = tempfile::tempdir().unwrap();
        skies(work.path(), &["new", "Golden"]);
        let solution = work.path().join("Golden");
        skies(&solution.join("src/Golden.Api"), &["g", "auth", flag]);
        assert_parity(tree, &solution, &["0001-auth"]);
    }
}

#[test]
fn crud_refuses_an_entity_that_is_not_tenant_scoped() {
    let work = tempfile::tempdir().unwrap();
    skies(work.path(), &["new", "Golden"]);
    let api = work.path().join("Golden/src/Golden.Api");
    skies(&api, &["g", "module", "Catalog"]);
    skies(&api, &["g", "entity", "Catalog", "Product"]);

    let output = Command::new(env!("CARGO_BIN_EXE_skies"))
        .args(["g", "crud", "Catalog", "Product"])
        .current_dir(&api)
        .output()
        .unwrap();

    assert_eq!(output.status.code(), Some(1));
    assert!(String::from_utf8_lossy(&output.stderr).contains("Product is not ITenantScoped"));
    assert!(!api.join("Modules/Catalog/Slices").exists());
}
