// GENERATED by `skies i18n` — do not edit. Re-run to regenerate after adding/removing a feature.
import { ptBR as deposit_ptBR, esES as deposit_esES, enUS as deposit_enUS } from "../deposit/deposit.i18n";
import { ptBR as items_ptBR, esES as items_esES, enUS as items_enUS } from "../items/items.i18n";
import { ptBR as transfer_ptBR, esES as transfer_esES, enUS as transfer_enUS } from "../transfer/transfer.i18n";

export const resources = {
  en: {
    "deposit": deposit_enUS,
    "items": items_enUS,
    "transfer": transfer_enUS,
  },
  pt: {
    "deposit": deposit_ptBR,
    "items": items_ptBR,
    "transfer": transfer_ptBR,
  },
  es: {
    "deposit": deposit_esES,
    "items": items_esES,
    "transfer": transfer_esES,
  },
} as const;
